# Header
menu:
  主页: "http://huzerui.com/"
  所有文章: /archives
  CV: "http://huzerui.com/cv"
  Sitemap: "/sitemap.xml"
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/alex1504"
  weibo: "http://weibo.com/alex1504"
  rss: "/atom.xml"
  douban: "http://www.douban.com/people/alex1504/" 
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
# google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/avatar.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends:
# W3CFuns: http://www.w3cfuns.com/
# W3CTech: http://www.w3ctech.com/
# Jquery之家: http://www.htmleaf.com/
# Stackoverflow: http://stackoverflow.com/
# Segmentfault: https://segmentfault.com/
# 优设: http://www.uisdc.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 品味简单的生活，爱的执着，像点聚成线，将生活变成艺术的勾勒。

#开启百度统计
baidu_tongji: true
